'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EventTable

    '''<summary>
    '''EventDateDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EventDateDDL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DateDDL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateDDL As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''MainPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MainPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''fvEventTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvEventTable As Global.System.Web.UI.WebControls.FormView

    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''SpeakerBio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SpeakerBio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddEvent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DeleteEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DeleteEvent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''WebPreview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WebPreview As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''AddEventPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AddEventPanel As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''l1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents l1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''NewEventDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NewEventDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CreateNewEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CreateNewEvent As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Mealcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Mealcount As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''MealCat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MealCat As Global.System.Web.UI.WebControls.SqlDataSource

    '''<summary>
    '''dsEvent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsEvent As Global.System.Web.UI.WebControls.SqlDataSource
End Class
